GeoscienceAustralia/dea-orchestration

lambda_functions/raijin_log_extractor/raijin_log_extractor.py
lambda_functions/raijin_log_extractor/test_raijin_log_extractor.py
lambda_modules/dea_es/__init__.py
lambda_modules/dea_es/dea_es/config.py
lambda_modules/dea_raijin/__init__.py
lambda_modules/dea_raijin/dea_raijin/auth/raijin_ssh.py
lambda_modules/dea_raijin/tests/lambda_commands_test.py
scripts/check-code.sh
setup.cfg

Disabled some of the pylint errors and made sure it was actually running against files.
120 character limit is defined in setup.cfg

fixing the linting checker

---

raijin_scripts/deploy/deploy.py

* Module file is left in read only state
* Modulefile name is truncated to be text following last dash; default is all text.

Made deploy modulefile read only. Truncated Module file name

---

lambda_functions/execute_fractional_cover/env_vars.json
lambda_functions/execute_stacker/env_vars.json
lambda_functions/execute_stacker/execute_stacker.py
lambda_functions/execute_stacker/requirements.txt
raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_stacker/run

Adds a lambda called `execute_stacker` for queueing and running stacker on the NCI. 
It uses the new `dea-stacker` command available from GeoscienceAustralia/digitalearthau#48. Input arguments are `year` and `app_config_file` provided in the lambda event, and `DEA_MODULE`, `PROJECT` and `QUEUE` from lambda environment variables.
The code is very similar to `execute_fractional_cover`, and adds both a simple lambda handler and a simple raijin script.

Add lambda for executing stacker on the NCI

---

lambda_functions/execute_ingest_js/README.md
lambda_functions/execute_ingest_js/handler.js
lambda_functions/execute_ingest_js/package.json
lambda_functions/execute_ingest_js/serverless.yml
lambda_functions/execute_stacker/execute_stacker.py
pylintrc
raijin_scripts/execute_ingest/run
scripts/check-code.sh

I've never been satisfied with the story for developing new lambdas and deploying them.
This PR takes a new approach, and uses Javascript code and the Serverless framework.
- This means the entire function fits in one simple file. (Could be simpler if my JS foo was stronger)
- Can be easily and repeatedly deployed with `sls deploy`
- The configuration for scheduling and IAM permissions is all contained within the `serverless.yml`.
- It should be able to be easily extended to support most of our NCI automation tasks with minimal code expansion.

Automate ingest on Raijin

---

lambda_functions/execute_ssh_command_js/serverless.yml

Update timeout value to be 5 mins (max) from default timeout of 6 seconds. This is done to avoid re-execution of the lambda function.

Add timeout to the serverless.yml

---

raijin_scripts/test_deaenv_fc/dea_testscripts/copy_fcyaml_files.sh
raijin_scripts/test_deaenv_fc/run
raijin_scripts/test_deaenv_ingest/dea_testscripts/cp_indingest_yaml_files.sh
raijin_scripts/test_deaenv_stats/dea_testscripts/cp_statsyaml_files.sh

Following are the changes in this PR:
1) Simplify sed expression to include 'sed -i -e' to modify in-place file we are sed-ing.
2) Remove ls5 fractional cover from the raijin script.

Simplify sed expression and remove ls5 fc

---

.travis.yml
lambda_functions/execute_ssh_command_js/README.md
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_ingest/run
raijin_scripts/execute_sync/run

During testing ingest process, it was noticed that a wall-time of 10 hours was not be sufficient for 2018. Due to this limitation, pbs scheduler was terminating the execution.
**Proposed solution:**
- Increase the wall-time to 40hrs for ingest process and 20hrs for sync process.
- Make the job queue as "normal" instead of "express" to allow increased wall-time.
- Update serverless.yml file to use latest dea module and do lambda scheduling cleanup.
- Update travis file to include deploy section

Increase ingest/sync walltime and add deploy section to travis

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_coherence/run

**Request for this pull request**
During ingest process, it was observed that duplicate datasets were ingested. To fix this issue, we need to use DEA-coherence tool to archive locationless datasets and sibling datasets. Need for automated coherence process by adding the configuration and raijin script to the dea-orchestration resulted in this PR.
1) Add execute_coherence script to the raijin scripts directory.
2) Add configuration for lambda submission of `dea-coherence` to the `serverless.yml` file.
Note: Tests were added as part of NCI environment test script

Add configuration and script for lambda submission of dea-coherence

---

raijin_scripts/execute_fractional_cover/run

FC app redirects events_path, logs_path, jobs_path and other logs to the directory structure in the following format (different to that of sync/ingest process):
`/g/data/v10/work/{output_product}/{task_type}/`
where,` task_type = create/sync/fc etc.`
Move the execution submission log file to FC work directory (mentioned above) to maintain consistency within previous FC work directory structure.

Redirect fc output submission log to work directory

---

raijin_scripts/deploy/dea-env/environment.yaml

It was removed due to broken dependencies, but should be fixed now.

Re-add rsgislib to the NCI environment

---

lambda_functions/execute_ssh_command_js/serverless.yml

Following schedule was used to automate lambda execution of Sync/Ingest/WOfS/FC at the NCI:
1) Run git pull production branch every _Monday @ 00:15 am (UTC time)_.
2) Run `dea-sync` every _Monday @ 00:30 am (UTC time)_.
3) Run `dea-submit-ingest` every _Tuesday @ 05:15 am (UTC time)_.
4) Run `datacube-wofs submit` every _Wednesday @ 14:15 pm (UTC time)_.
5) Run `datacube-fc submit` every _Wednesday @ 14:15 pm (UTC time)_.

Automate lambda schedule to run Sync/Ingest/WOfS/FC at the NCI

---

raijin_scripts/deploy/README.md
raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea-env/modulespec.yaml
raijin_scripts/deploy/dea/modulespec.yaml
raijin_scripts/deploy/reinstall_miniconda.sh

When `rasterstats `and `jupyter `lab extension modules were added to the `environment.yaml` file, `dea-env` build fails while creating a new `dea `build or sometimes some of the python packages would downgrade. 
1) Update `reinstall_miniconda` file to check if `nvm `package is installed (if not install the package). This is to ensure that `jupyter` `lab` extension modules are installed and build correctly.
2) Add `rasterstats` to the `environment.yaml` file and add dependencies with the latest version.
3) Add dependencies for `jupyter` `lab` issue and improve logging.
4) Redirect the `subprocess` output to a log file and store the log file in the build directory.
5) Update user instructions in `README.md` file for building dea …

Add rasterstats/jupyter lab extension modules and fix build issue

---

lambda_functions/execute_ssh_command_js/serverless.yml

Automation for Landsat 7 products were not added to the serverless configuration file.
**Proposed solutions**
Automate Landsat 7 product process by adding the configuration settings in the `serverless.yml` file

Automate ls7 products processing

---

lambda_functions/execute_ssh_command_js/serverless.yml

On failure, Lambda functions being invoked asynchronously are retried at least 3 times, after which the event may be rejected. Timeout set in the `serverless.yml` file was 2 minutes. During each retries `lambda` function was executed and this was causing `AWS` `lambda` trigger multiple times.
**Proposed workaround**
Increase the timeout in the `serverless.yml` file to 5 minutes (max) from 2 minutes.

Increase cron timeout to 5 minutes from 2 minutes

---

raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_wofs/run

**Reason for pull request**
During lambda execution, it was noticed that the database query and `fc`/`wofs` execution would take more than 5 minutes. This was causing the lambda execution to timeout and trigger a duplicate execution of `fc`/`wofs`.
Move database query and `fc`/`wofs` execution to background process.

Push database query and fc/wofs execution to background

---

raijin_scripts/test_deaenv/run

Qsub job for `stats` was dependent on every `stats` config file. This was causing the stats testing wait for long time (due to normal queue qsub job).
Make `stats` pbs job run after `wofs` job is completed.

Make stats qsub job run after wofs job

---

raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/reinstall_miniconda.sh

Add `xgboost` and `joblib` dependencies to the python `dea` environment module. Also, log the conda package versions packaged within the `dea-env` module in the log file.

Add dependencies (xgboost and joblib)

---

raijin_scripts/execute_sync/run
raijin_scripts/test_deaenv/dea_testscripts/datacube-fc.sh
raijin_scripts/test_deaenv/dea_testscripts/datacube-stats.sh
raijin_scripts/test_deaenv/dea_testscripts/datacube-wofs.sh
raijin_scripts/test_deaenv/dea_testscripts/dea-submit-ingest.sh
raijin_scripts/test_deaenv/dea_testscripts/dea-sync.sh
raijin_scripts/test_deaenv/dea_testscripts/pbs_nbconvert_script.sh

Email notification of `pbs` job that `successfully executed` or `failed to execute` or `aborted`, are missing for `dea-sync` script and `test_deaenv` scripts.
**Proposed solutions**
- Update the following scripts to notify `success`/`failure`/`aborted` status via email:
- `raijin_scripts/execute_sync/run`
- `datacube-stats.sh`
- `dea-sync.sh`
- `pbs_nbconvert_script.sh`

Add email monitoring for pbs jobs

---

raijin_scripts/deploy/dea/datacube-ensure-user.py

**Reason for pull request**
Comments within the `pgpass` file would break the existing logic within `datacube-ensure-user.py` file.
1) Update the code to handle comments within `pgpass` file.
2) Remove logging of connection successful status when user loads the `dea` module.

Handle comments within pgpass file

---

raijin_scripts/test_deaenv/dea_testscripts/dea-sync.sh
raijin_scripts/test_deaenv/run

To speedup the test execution, start `stats` tests after `wofs` scripts have completed execution. Existing script would wait for long time before all the test scripts have completed the test runs.
Store `wofs` `qsub` job id to a variable and use this as a dependency condition for `qsub` job scheduling. Also, rename `sync` cache folder to be unique to avoid duplicates.

Make stats test run after wofs tests

---

raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea-env/modulefile.template
raijin_scripts/deploy/dea-env/modulespec.yaml
raijin_scripts/deploy/dea/modulefile.template
raijin_scripts/deploy/dea/modulespec.yaml
raijin_scripts/test_deaenv/dea_testscripts/dea-sync.sh
raijin_scripts/test_deaenv/run

`PYTHONUSERBASE`, `PATH`, or `PYTHONPATH` are being set to the version of `dea` module that should have been set based on the version of `dea-env` module. This would attempt to install the extra python packages into the `dea` module path instead of their `home` directory. Also, local `home` directory name is referring to `dea` module instead of `dea-env` module.
- Update module template files to fix `path` issue.
- Add the following new python packages to the `dea-env` module.
- `mpi4py`
- `rasterstats`
- `keras`
- `rios`
- `checksumdir`
- `parse`

Fix inconsistent dependency issue and add python packages

---

raijin_scripts/test_deaenv/dea_testscripts/dea-sync.sh

Cache directory name had $RANDOM variable that generated different cache directory names. This was causing sync test to fail.
Create a new variable and use this variable within the script

Fix cache dir issue

---

raijin_scripts/deploy/dea-env/modulefile.template
raijin_scripts/deploy/dea/modulefile.template

Flexibility to just load `dea-env` and work with user installed python packages was not feasible in the earlier implementation. Need to allow user to load `dea-env` or `dea` and do a `pip install` to install custom packages is a likely use case.
- Remove duplicate entries of `HOME` directory in `PYTHONPATH` and `PATH` and prepend `HOME` directory at the top.

Set HOME directory at the top of the PATH list

---

lambda_functions/execute_ssh_command_js/handler.js
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_coherence/run
raijin_scripts/execute_notify_on_error_ds/run

Existing database contains many duplicate datasets, locationless datasets, and downstream datasets with locationless source dataset. We need to periodically check such inconsistencies in the database and log erroneous dataset info into a `CSV` file. Also run a execute_notify script to see if we have any such erroneous datasets in the `CSV` file, then notify user via slack channel to take further action on such datasets.
1) Automate execution of `dea-coherence` tool to check `locationless`, `sibling`, and `erroneous downstream` datasets. And if we have any mismatches, log the same into a `CSV` file.
2) Automate notify script (scheduled daily) to check for any new `CSV` file and if any, then upload the `CSV` file to `S3` bucket and notify via slack channel (`#dea-orchestration` channel).

Automate database inconsistency checks

---

lambda_functions/execute_ssh_command_js/serverless.yml

* Indentation issue caused the events to be nested under the environment (which is wrong).
* Broke deployment because it created environment variables that weren't strings (due to nesting).

Fix indentation for s2ard execution

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_s2ard/run

* Fixing 2 typos in the configuration files (--dry-run and --year)
* Fixing dates to be a cumulative offset (as per execution code)

typo fix in raijin-run; fix dates in serverless.yml

---

lambda_functions/execute_ssh_command_js/handler.js
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_clean/run
raijin_scripts/execute_coherence/run
raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_ingest/run
raijin_scripts/execute_notify_on_error_ds/run
raijin_scripts/execute_sync/run
raijin_scripts/execute_wofs/run

Duplicate files on the disc was indexed by the `sync` tool during weekly orchestration on `landsat` scenes.
Also, when `sync` tool detects that the file is no longer available on the `NCI` file system, orchestration `sync` tool updates the location in the index.
These processes created a **domino effect** resulting in large number of `duplicate datasets`/`locationless parent`/`archived parent with derived children`.
Datasets with such discrepancies needs to be reported and/or `archive`/`delete from file system`. And update the `index`.
Following work flow is used to clean up erroneous datasets:
1) Update `execute_coherence` script to report all such erroneous datasets.
2) Automate erroneous dataset reporting via `serverless` config.
3) Validate reported datasets and archive them manually …

Cleanup duplicate/locationless parent/archived parent with derived children

---

lambda_functions/simple_s3_pypi/README.md
lambda_functions/simple_s3_pypi/make_public.py
lambda_functions/simple_s3_pypi/serverless.yml

We have set up an (S3 Inventory)[https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html]
on the `dea-public-data` S3 bucket, and wish for it to be public.
Unfortunately, AWS doesn't provide an easy way to do this. Even if the target bucket is public,
the objects are created and owned by an AWS process, so don't inherit the permissions.
This PR adds a lambda which watches for new objects in the inventory bucket, and then
makes them public.

Keep dea-public-data-inventory public

---

lambda_functions/execute_ssh_command_js/serverless.yml

Extend `dea-sync` to sync and index `S2A` `ARD` and `S2B` `ARD` granule products weekly.
1) Sync on `s2_ard_granule` is scheduled to run every Thursday 8:10pm AEST.
2) Update `dea` module to the latest one

Update sls config to automate s2 ard granule

---

lambda_functions/execute_ssh_command_js/serverless.yml

Sentinel-2 definitive production will be paused until we are able to source a definitive water vapour dataset.

Disabling level-2 trigger; need to wait for updated water vapour data 

---

lambda_functions/stac/README.md
lambda_functions/stac/serverless.yml
lambda_functions/stac/stac.py
lambda_functions/stac/stac_check.py
lambda_functions/stac/stac_deploy.tf

It was decided that `event processing pipeline` for `STAC item` processing now require feeds from an existing `SNS topic` that publishes `S3 object creation events` in an `S3` bucket. This PR updates the `terraform` script that deploy `SQS` infrastructure and the `lambda` function to do improved filtering. Further documentation updates are given in `README.md`. Batch processing scripts do not require updates. 
[x] No `SNS filtering` is performed since filtering based on the `message` is not available. Instead filtering is performed within the lambda function itself.

Stac check

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_cog_conversion/run
scripts/git_pull

Automate `cog conversion` for `WOfS` product.
- Update serverless config file to schedule new raijin script, `execute_cog_conversion`.
- Add new raijin script to `qsub` and convert `netCDF` files to `COG` format.
- Update `scripts/git_pull` script to fetch latest revision of `COG-Conversion` git repository.

Automate wofs cog

---

lambda_functions/execute_ssh_command_js/handler.js
lambda_functions/execute_ssh_command_js/package.json
lambda_functions/execute_ssh_command_js/serverless.yml

Sentinel 2 ARD granules for all the years are packaged into one single directory as follows:
`/g/data/if87/datacube/002/S2_MSI_ARD/packaged`.
This breaks the orchestration process for `dea-sync` on S2 ard products. And would add more manual editing of serverless configuration file whenever new granules are packaged within the `packaged` directory.
1. Update `handler.js` function to expand `path` `glob` based on process environment variables and then pass the same to the `ssh` execution command string.
2. Add a delay of `1s` before execution new `ssh` command. This is done to ensure that `dea-sync` does not fail while accessing same cache file when we schedule all the `ssh` command string without any delay.
3. Update  `handler.js` function for processing `Landsat` scenes in lines with `S2 …

Process s2 ard and landsat scene dataset sync in a more efficient way

---

lambda_functions/execute_ssh_command_js/handler.js
lambda_functions/execute_ssh_command_js/package.json
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_cog_conversion/run

1) Update `lambda` function to prevent duplicate execution of `ssh` `command` with the help of `underscore` `npm` package.
2) Fix typo in `raijin_scripts/execute_cog_conversion/run` script and `lambda_functions/execute_ssh_command_js/serverless.yml` file .
3) Add `underscore` `npm` package in `lambda_functions/execute_ssh_command_js/package.json` file.

Remove multiple ssh command executions

---

lambda_functions/execute_ssh_command_js/handler.js
lambda_functions/execute_ssh_command_js/serverless.yml
lambda_functions/simple_s3_pypi/genindex.py
raijin_scripts/deploy/build_environment_module.py
raijin_scripts/execute_cog_conversion/run
raijin_scripts/execute_sync/run

Lambda function had too many product specific processing code. This will make it hard to maintain, when we have more new products added to the orchestration configuration.
- Simplify lambda function within `lambda_functions/execute_ssh_command_js/handler.js` file by moving product specific processing into serverless configuration file.
- Update `lambda_functions/execute_ssh_command_js/serverless.yml` configuration file to manage product specific setting.
- Update `raijin_scripts/execute_cog_conversion/run` file to format `time` `query` and process entire time range as a single `qsub` command. 
- Update `raijin_scripts/execute_sync/run` file to submit `qsub` jobs broken down to individual year as per the configuration setting (`year`).
- Fix `fstring` interpolation failures in …

Clean lambda function

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_s2ard/run

* Re-enables sentinel-2 processing with a version increment
* Version increment includes configuration to include averaged water vapour datasets as a fallback option

Added version parameter to execute script; re-enabling s2

---

lambda_functions/stac/requirements.txt
lambda_functions/stac/stac.py
lambda_functions/stac/stac_check.py

Some products store the `CRS` string in `ESRI/OGC WKT` format rather than as an
`EPSG` code. `Data cube CRS` or `Geometry` classes are hard to use in AWS
Lambdas due to the large size of `GDAL` or `rasterio`. Together with other
dependencies, they exceed the 50MB size limit of AWS Lambdas files). 
Instead, we can use the pure python `pycrs` library to parse `crs strings` to `proj4` format.

Refactored valid data projection code for STAC lambdas

---

raijin_scripts/execute_sync/run

Incorporate suggestion from #108 (Replace `_copy/paste + echo_`, with `built-in` `shell` command `set -/+x`). 
Multiple `sync` jobs may fail, if two jobs are running at the same time, as one job may attempt to create the cache directory after the other's job has already created.
1. Replace `_copy/paste + echo_`, with built in shell command `set -/+x`.
2. Create unique `cache` directory for the requested `sync` job.

Use set -x for echo logging and create unique cache dir

---

raijin_scripts/deploy/dea-env/environment.yaml

`Datacube` `ingest`, `datacube-fc`, `datacube-wofs`, and `datacube-stats` apps had issues with latest revision of `dask`, `distributed`, and `redis-py` `python` `conda` packages. 
Revert `dask`, `distributed`, and `redis-py` `conda` packages to last know working revisions.
- Workaround for [[https://github.com/GeoscienceAustralia/digitalearthau/issues/205](url)] and [[https://github.com/opendatacube/datacube-core/issues/658](url)]

Patch dea env

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/deploy/dea/datacube-ensure-user.py
raijin_scripts/execute_sync/run

`Sentinal 2` `ARD` `A/B` `sync` orchestration job pushed hundreds of jobs to the `PBS` `job` `queue`. This was causing significant delays in `qsub` job execution.
**Root cause:** `sync` path in a single `qsub` job for `s2_ard_granule` was submitted without grouping. 
**for ex.** a single `qsub` was submitted to process datasets on a daily basis instead of grouping them.
- Group number of days and then submit sync job. This way the max number of `pbs` jobs submitted in a year for `s2_ard_granule` is reduced to `48` from `365`.
- Update orchestration year to process `2019` year.
- Fix `pylint` error.

Fix s2ard sync issue

---

raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/env_requirements.txt
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea-env/modulespec.yaml
raijin_scripts/deploy/dea-env/pip_install_packages.txt
raijin_scripts/deploy/reinstall_miniconda.sh
raijin_scripts/deploy/requirements.txt

`dea/20181015` require updated python `conda` packages. Also, a fix for `dea-env` build dependencies issues.
1. `raijin_scripts/deploy/build_environment_module.py`: Refactor code and update comments within the file
2. `raijin_scripts/deploy/dea-env/environment.yaml`: To resolve issues with `dea-env` build packages, ensure packages are installed using `conda` instead of `pip`. If packages are not available within `conda` distribution packages, go with `pip` install.
3. `raijin_scripts/deploy/dea-env/environment.yaml`: Add new python conda packages: `openmpi`, `qgis`, `rsgislib`
4. `raijin_scripts/deploy/dea-env/modulespec.yaml`: Install `pip` packages during environment packaging
5. `raijin_scripts/deploy/dea-env/pip_install_packages.txt`: Add the following packages as part of pip install …

Fix dea env issues

---

raijin_scripts/deploy/dea-env/environment.yaml

Useful for accessing dask dashboard when using notebook via ssh port forward

Install jupyter-server-proxy

---

.travis.yml
lambda_functions/stac/requirements.txt
raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea/datacube.conf
raijin_scripts/deploy/dea/modulespec.yaml
raijin_scripts/deploy/dea/requirements.txt
raijin_scripts/test_deaenv/run
scripts/check-code.sh

Following are the changes implemented within this PR:
1. In `raijin_scripts/deploy/build_environment_module.py` file:
- Add `--no-warn-script-location` flag to ignore pip install path for `odc` packages. `pip` `PATH` used is from `dea-env` whereas `pip` path is expecting the `dea` bin path to be  added to `PATH`
- Update code to install `dea-proto` `odc.*` packages
2. In `raijin_scripts/deploy/dea/datacube.conf` file:
- Add config setting for `c3` samples
3. In `raijin_scripts/deploy/dea/modulespec.yaml` file:
- Add `dea-proto` pip install paths
4. In `raijin_scripts/test_deaenv/run` file:
- Remove redundant logging

Install dea-proto odc ui's

---

raijin_scripts/deploy/dea-env/environment.yaml

[Zarr](https://zarr.readthedocs.io/en/stable/) is something we have been meaning to play with for a while now. It may simplify the intermediate steps in our workflow by enabling multiprocess write to disk.

Add Zarr to dea-env

---

lambda_functions/automate_cubedash_db_update/handler.py
lambda_functions/automate_cubedash_db_update/serverless.yml
lambda_functions/automate_cubedash_db_update/test_handler.py
raijin_scripts/execute_update_cubedash_config/run

`SNS` topic can receive `ows`/`nci` database name. Depending on the database name, `ows`/`nci` explorer configuration file in `datakube-apps` `bitbucket` repo is to be updated.
- In `serverless.yml` file, use separate explorer configuration file
- In `handler.py` file, read the database name from SNS topic. Depending on the database name,  configuration file in `bitbucket` repo shall be updated
- Update pytests

Update ows/nci database based on SNS message

---

lambda_functions/automate_cubedash_db_update/handler.py
lambda_functions/automate_cubedash_db_update/serverless.yml
lambda_functions/automate_cubedash_db_update/test_handler.py

SNS notification message now has the bitbucket branch name prefixed to ows database name. 
This information would help automation to correctly update the helm chart within the respective bitbucket branch

Process bitbucket branch name from sns notification

---

raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea-env/modulefile.template
raijin_scripts/deploy/dea-env/modulespec.yaml
raijin_scripts/deploy/dea-env/requirements.txt

1. Add the following python packages to dea environment yaml file:
- descartes
- flake8
- anaconda::redis
- autopep8
- jupyterlab-dash
- openmp
- pytorch::pytorch
- pytorch::torchvision 
- anaconda::cudatoolkit
- yapf
- isort
- jupyterlab_code_formatter
2. Install `pyproj` using conda instead of pip
3. Fix `PROJ_LIB` template path issue
4. Pip install `hdstats` package from `s3`
5. Add `jupyterlab code formatter`  and `jupyterlab dash` labextensions
6. Minor fixes to environment module python file

Add new python packages to dea-env

---

lambda_functions/automate_cubedash_db_update/package.json
lambda_functions/nci_monitoring/package.json
lambda_functions/stac/package.json
scripts/check-code.sh
scripts/deploy.sh

- Only report test coverage for the current directory, not every single installed python file
- `chmod +x` the deployment script to see if it'll run on Travis-CI

Travis Reporting and Deployment Fixes

---

raijin_scripts/execute_fractional_cover

Somehow `datacube-fc` app was not able to find `datacube` config path from the environment variables in `Gadi` compute node. 
Explicitly pass `datacube` config path as an input argument value to `datacube-fc` `submit` command

Pass datacube config file path

---

scripts/deploy.sh

- Add `--overwrite` argument to the `sls config credentials` command

Fix serverless aws configuration issue

---

lambda_functions/execute_ssh_command_js/serverless.yml

- Sentinel-2 Definitive processing job requires stable wagl module on Gadi
- The existing stable `wagl` module (`wagl/5.3.1`) is broken on Gadi
- Turn off `Sentinel-2 Definitive` orchestration jobs till we have stable `wagl` module from `ARD` team

Turn off S2-definitive jobs till we have working wagl module on Gadi
