GeoscienceAustralia/dea-orchestration

scripts/remote

Allows the script to be executed without ssh_original_command

adding ability for devs to test commands at remote entry point

---

lambda_functions/job_monitor/requirements.txt
scripts/remote
scripts/run_lambda

Fix you helped be find earlier; allows the script to interpret args as an array.

adding fix for local execution of scripts

---

raijin_scripts/deploy/deploy.py

- Pip installed numpy at different folder using latest version of numpy
- Changing PYTHONPATH to locate installed numpy
- After installing tarzip folder change the PYTHONPATH to destination folder

Changes to Deploy script to automatically deploy FC

---

README.md

Key requirements were reduced from 3 -> 2

correcting ssh key requirements in documentation

---

raijin_scripts/execute_fractional_cover/run

updated args assignment in execute_fractional_cover raijin script

---

lambda_functions/execute_ssh_command_js/serverless.yml

Add production environment S3 bucket name in the serverless.yml file.

Add S3 bucket name for production environment

---

lambda_functions/deploy_test_deaenv_js/README.md
lambda_functions/deploy_test_deaenv_js/serverless.yml
lambda_functions/execute_ssh_command_js/README.md
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_ingest/run
raijin_scripts/execute_stacker/run
raijin_scripts/execute_sync/run

Add aws profile configuration as part of serverless.yml file. Also, update the readme file to include more instruction on how to create and use aws profile while deploying.

Add aws profile

---

raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_ingest/run
raijin_scripts/execute_stacker/run
raijin_scripts/execute_sync/run

Create a directory based on the products, for storing execution logs (if directory does not exists).

Create output directory for storing logs

---

raijin_scripts/execute_sync/run

Update run file to schedule dea-sync for the year 2018 of ls7_nbar/t_scenes, ls8_nbar/t_scenes, ls7_pq_scenes, and ls8_pq_scenes products.

Modify execute_sync script to perform dea-sync of ls7/8 nbar and pq 2018 scenes

---

lambda_functions/deploy_test_deaenv_js/serverless.yml
raijin_scripts/test_deaenv_fc/dea_testscripts/copy_fcyaml_files.sh
raijin_scripts/test_deaenv_fc/run
raijin_scripts/test_deaenv_index_ingest/dea_testscripts/cp_indingest_yaml_files.sh
raijin_scripts/test_deaenv_index_ingest/dea_testscripts/index_and_ingest.sh
raijin_scripts/test_deaenv_index_ingest/run
raijin_scripts/test_deaenv_nbconvert/dea_testscripts/nbconvert_execute.sh
raijin_scripts/test_deaenv_nbconvert/run
raijin_scripts/test_deaenv_stats/dea_testscripts/cp_statsyaml_files.sh
raijin_scripts/test_deaenv_stats/run
raijin_scripts/test_deaenv_sync/datacube_config.conf
raijin_scripts/test_deaenv_sync/run

Following are the changes within this pull request:
1) Add new test_deaenv_sync to raijin scripts directory.
2) Add test_deaenv_sync lambda function to deploy_test_deaenv_js/serverless.yml file.
3) Add input parameters as a configurable inputs to the lambda functions.
4) Simplify output logging directory structure within the raijin scripts.
5) Remove unwanted code within the raijin scripts.

Add test_deaenv_sync to raijin scripts directory and update raijin deaenv test scripts

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_sync/run

Change trasharchive to trasharchived in serverless.yml file and raijin script.

Fix typo in serverless.yml file and raijin script

---

.travis.yml
lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_fractional_cover/run

Reason for the pull request
Raijin script execute fractional cover need update for latest changes and fc lambda function in serverless file is missing.
Solution:
Update fc raijin script to be up to date and add execute fc to serverless yml file.

Update fractional cover and serverless file to include fc

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_wofs/run

Add aws lambda automation for wofs

Automate wofs execution using aws lambda

---

lambda_functions/execute_ssh_command_js/serverless.yml

Update schedule to process new ops data

Update schedule to process ops data

---

lambda_functions/execute_ssh_command_js/serverless.yml

Update the latest `dea` module in the serverless configuration file.
New `dea` module has many bug fixes and improvements.

Update latest dea module

---

raijin_scripts/deploy/dea/datacube-ensure-user.py

It wasn't correctly handling `.pgpass` files with blank lines in them.

Fix ensure user script

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_coherence/run
raijin_scripts/execute_fractional_cover/run
raijin_scripts/execute_notify_on_error_ds/run
raijin_scripts/execute_sync/run
raijin_scripts/execute_wofs/run

Implement review comments from `PR#75`
1) Add an argument `--webhook` to `execute_notify_on_error_ds` `lambda` function and configure the hook `URL` in `SSM`.
2) Update `exit` codes to `non-zero` such that the exit code get passed back through `lambda` and `cloud watch` to notify if script has `failed`.

Implement review comments from PR75

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_s2ard/run

Features:
* Adds automation commands for the sentinel2ard generation
* One entrypoint to handle level1 yaml generation; level2 production
Cron times were determined arbitrarily, enabled is set to false for verification.
Any informed advice on handling processing dates, ranges and scheduling is welcome.

Committing s2 automation processing commands

---

.travis.yml
raijin_scripts/deploy/reinstall_miniconda.sh
scripts/check-code.sh
scripts/deploy.sh

* Uses serverless package (a function to generate deployment artifacts) to check the configuration file (serverless.yml) on the CI.

serverless cfg check

---

lambda_functions/execute_ssh_command_js/serverless.yml
lambda_functions/job_monitor/job_monitor.py
raijin_scripts/deploy/dea/datacube-ensure-user.py
raijin_scripts/execute_s2ard/run

- Correcting year range in bash script file
- Add s2ard description
- Corrects dates in run files; reduces lag in processing

Updating trigger times on s2 execution

---

raijin_scripts/execute_s2ard/run

* Improves documentation in the script
* Adds parameter to capture resource requirements for the find command
* Adds generic locations for the workdir and logdir required by wagl
After this change is ready I'll merge master into production if that's okay.

Moving workdir, logdir paths from user to system paths

---

lambda_functions/execute_ssh_command_js/serverless.yml
raijin_scripts/execute_s2ard/run

* Happy to turn on the sentinel-2 processing ongoing; just need a few more resources for the find command

Enabling s2 production; increase resource cap for fs find

---

raijin_scripts/execute_cog_conversion/run

Fix typo in raijin script

---

lambda_functions/execute_ssh_command_js/serverless.yml

Move `sync`/`ingest`/`fc`/`wofs`/`cog` execution setting to improved workflow `serverless` file (`Step function` `serverless` config file)

Remove LS7 and LS8 AGDC ingest settings

---

lambda_functions/execute_ssh_command_js/serverless.yml

Update `S2` `ard` `sync` event to run every Friday

Update s2 ard sync schedule

---

raijin_scripts/deploy/build_environment_module.py
raijin_scripts/deploy/dea-env/environment.yaml
raijin_scripts/deploy/dea-env/modulefile.template
raijin_scripts/deploy/dea-env/modulespec.yaml
raijin_scripts/deploy/dea-env/pip_install_packages.txt
raijin_scripts/deploy/dea/modulespec.yaml
raijin_scripts/test_deaenv/dea_testscripts/copy_yaml_files.sh
raijin_scripts/test_deaenv/dea_testscripts/datacube-fc.sh
raijin_scripts/test_deaenv/dea_testscripts/datacube-stats.sh
raijin_scripts/test_deaenv/dea_testscripts/datacube-wofs.sh
raijin_scripts/test_deaenv/dea_testscripts/dea-submit-ingest.sh
raijin_scripts/test_deaenv/dea_testscripts/dea-sync.sh
raijin_scripts/test_deaenv/dea_testscripts/pbs_nbconvert_script.sh
raijin_scripts/test_deaenv/dea_testscripts/requirements_met.ipynb
raijin_scripts/test_deaenv/run

1. `nbdime` -- visual diff tool for notebooks
2. `git` -- stage/commit directly from jupyterlab
3. `leaflet` -- `ipyleaflet` requires extra extension to work in JupyterLab

Add more Jupyter extensions

---

lambda_functions/automate_cubedash_db_update/serverless.yml

Give `lpgs` user permission to `ssm:GetParameter` operation

Fix ssm permission issue

---

lambda_functions/execute_ssh_command_js/serverless.yml

Suspend jobs till data migration is completed

Suspend S2 ARD processing and sync jobs

---

lambda_functions/s3stat-automation/requirements.txt
lambda_functions/s3stat-automation/s3_monthly_update/handler.py
lambda_functions/s3stat-automation/serverless.yml

- Add `shapely` to requirements.txt
- In `s3_monthly_update/handler.py`, fix `CSV_FILE` file access issue when lambda function was attempting to write to a temp file
- In `serverless.yml` file, fix typo and cron job schedule

Fix lambda function issues

---

raijin_scripts/execute_fetch_job_ids

- File extension `r-man2` is not a valid extension on Gadi

Fix gadi pbs file extension

---

raijin_scripts/deploy/dea/datacube-ensure-user.py

I mostly want to check what happens on Travis, and see if the code deploys to the NCI.

Reorder methods in user creation script

---

lambda_functions/nci_monitoring/serverless.yml
lambda_functions/stac/serverless.yml
scripts/deploy.sh

Lets see what breaks.

---

airflow/Dockerfile
airflow/Makefile
airflow/README.md

No automation, just manual Docker image building and pushing

Add airflow

---

airflow/cognito_auth.py

Initial pattern based on Google OAuth.

#170 add cognito auth support

---

nci_environment/dea-env/environment.yaml

- Had to remove following libs:
- mkl      - not sure why it doesn't work
- pytorch  - doesn't work because of mkl not working
- rsgislib - doesn't work with geos 3.8 and other things don't work with older
- proj4    - replaced by proj
- Pinned geo libs and psycopg2
- Moved some things from pip to conda
- Removed some transient dependencies from the list (prometheus_client)
- Un-namespaced some packages

Tweaking dependencies to make it work

---

nci_environment/dea-env/environment.yaml
nci_environment/dea-env/modulespec.yaml

1. Fixed bokeh
2. Removed pins for geo libs
3. Removed reinstallation of extension pulled in by conda
4. Moved some `dask-labextension` into conda land
5. Not enabling conda installed server extensions

Fixes for jupyterlab build

---

nci_environment/dea-env/environment.yaml
nci_environment/dea-env/modulefile.template
nci_environment/dea-env/modulespec.yaml
nci_environment/dea/modulefile.template

- Also remove `module load udunits` from template
- `sidecar` for better mapping experience in the notebook
- `ipycanvas/ipyevents` not currently used but could be useful for ML annotations
- `pydotplus` for this https://github.com/GeoscienceAustralia/dea-notebooks/issues/581

Adding sidecar and some other things
